name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: dependencies
        run: pipx install rendercv

      - name: generate
        run: make archive

      - name: store artifact
        uses: actions/upload-artifact@v4
        with:
          name: resumes
          path: build/resumes.zip
