name: Deploy

on:
  push:
    tags: ['v*']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: dependencies
        run: pipx install rendercv

      - name: deploy
        run: make -e deploy
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

      - name: generate archive
        run: make archive

      - name: store artifact
        uses: actions/upload-artifact@v4
        with:
          name: resumes
          path: |
            build/resumes.zip
            build/**.pdf
            build/**.html
