name: Deploy

on:
  push:
    tags: ['v*']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: deploy
        run: make -e deploy
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

      - name: store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resumes
          path: |
            build/kevin_kin-foo_en.html
            build/kevin_kin-foo_en.pdf
            build/kevin_kin-foo_fr.html
            build/kevin_kin-foo_fr.pdf
