name: Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: parse
        run: make resume

      - uses: anishathalye/proof-html@v2
        name: check html links
        with:
          directory: ./build
          connect_timeout: 5
          retries: 1
          check_css: false
          check_favicon: false
          check_opengraph: false
          ignore_url: |
            https://linkedin.com/in/kin-foo
            https://enix.io/fr/formation-kubernetes/
